const JWTSECRETKEY = process.env.JWT_SECRET
const JWTSECRETKEYREFRESH = process.env.JWT_SECRET_REFRESH

const JWTEXPIRATION = process.env.JWT_EXPIRATION


export {
    JWTSECRETKEY,
    JWTSECRETKEYREFRESH,
    JWTEXPIRATION
}